package auto

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"regexp"
	"strconv"
	"strings"

	"github.com/blang/semver"
	"github.com/rancher/charts-build-scripts/pkg/lifecycle"
	"github.com/rancher/charts-build-scripts/pkg/logger"
)

// versions holds all the version components required to calculte the next chart version.
// It distinguishes between the application's version (from upstream)
// and the repository-specific prefix
type versions struct {
	latest              *version // the most recent non-RC application version found in the repository
	latestRepoPrefix    *version // the most recent non-RC repository-specific (charts repository)
	toRelease           *version // new calculated application version
	toReleaseRepoPrefix *version // new calculated repository-specific version
	currentRCs          []rc     // list of existing RC versions
}

// rc Release Candidate, composed of a repository prefix and an application version.
type rc struct {
	repoPrefix *version
	appVersion *version
}

// version encapsulates a version string and its parsed semantic version representation.
type version struct {
	txt string
	svr *semver.Version
}

// updateSemver is a helper to transform a string version in its semver object representation.
func (v *version) updateSemver() error {
	newSemver, err := semver.Make(v.txt)
	if err != nil {
		return err
	}
	v.svr = &newSemver
	return nil
}

// updateTxt is a helper to transform a semver object into its string form.
func (v *version) updateTxt() {
	v.txt = v.svr.String()
}

// calculateNextVersion will calculate the next version to bump based on the latest version
// if the chart had a patch bump, it will increment the patch version for the repoPrefixVersion
// if the chart had a minor or major bump, it will increment the minor version for the repoPrefixVersion
// the major repoPrefixVersion is only bumped when Rancher version is bumped.
func (b *Bump) calculateNextVersion(ctx context.Context, versionOverride string, newChart bool) error {
	logger.Log(ctx, slog.LevelInfo, "calculate next version")
	var targetVersion string

	if !isRancherChartVersion(versionOverride) {
		if newChart {
			if err := b.netNewVersion(); err != nil {
				return err
			}
		} else {
			// load versions and parse the repository prefix versions from them
			if err := b.loadVersions(); err != nil {
				return err
			}

			// check and parse the versions before building the new version
			if err := b.applyVersionRules(versionOverride); err != nil {
				return err
			}

			logger.Log(ctx, slog.LevelInfo, "checking current RC's")
			currentRCs, err := getCurrentRCsFromIndex(b.assetsVersionsMap[b.target.main], b.versions.toReleaseRepoPrefix.txt)
			if err != nil {
				return fmt.Errorf("failed checking RC's for version: %s - %w", b.target.main, err)
			}
			if len(currentRCs) > 0 {
				b.versions.currentRCs = currentRCs
				logger.Log(ctx, slog.LevelWarn, "RCs present", slog.Any("amount", len(currentRCs)))
				for _, rc := range currentRCs {
					rcVersion := rc.repoPrefix.txt + "+up" + rc.appVersion.txt
					logger.Log(ctx, slog.LevelDebug, "", slog.String("version", rcVersion))
				}
			}

			logger.Log(ctx, slog.LevelDebug, "", slog.String("latestVersion", b.versions.latest.txt))
			logger.Log(ctx, slog.LevelDebug, "", slog.String("latestRepoVersion", b.versions.latestRepoPrefix.txt))
			logger.Log(ctx, slog.LevelDebug, "", slog.String("toReleaseVersion", b.versions.toRelease.txt))
			logger.Log(ctx, slog.LevelDebug, "", slog.String("toReleaseRepoVersion", b.versions.toReleaseRepoPrefix.txt))
		}

		targetVersion = b.versions.toReleaseRepoPrefix.txt + "+up" + b.versions.toRelease.txt
	} else {
		targetVersion = versionOverride
	}

	targetSemver := semver.MustParse(targetVersion)
	b.target.bumpVersion = targetVersion
	b.releaseYaml.ChartVersion = targetVersion
	b.Pkg.AutoGeneratedBumpVersion = &targetSemver

	logger.Log(ctx, slog.LevelInfo, "calculated bump", slog.String("version", b.target.bumpVersion))
	return nil
}

func isRancherChartVersion(s string) bool {
	// Pattern explanation:
	// ^\d+\.\d+\.\d+     - Rancher version (e.g., 107.0.2)
	// \+up               - Literal "+up" separator
	// \d+\.\d+\.\d+$     - Upstream version (e.g., 0.13.2)
	pattern := `^\d+\.\d+\.\d+\+up\d+\.\d+\.\d+$`
	matched, _ := regexp.MatchString(pattern, s)
	return matched
}

// netNewVersion will calculate the first version for a previous non-existing chart
func (b *Bump) netNewVersion() error {
	b.versions = &versions{
		toRelease:           &version{},
		toReleaseRepoPrefix: &version{},
	}

	b.versions.toRelease.txt = b.Pkg.Chart.GetUpstreamVersion()
	if b.versions.toRelease.txt == "" {
		return errChartUpstreamVersion
	}
	if err := b.versions.toRelease.updateSemver(); err != nil {
		return err
	}

	b.versions.toReleaseRepoPrefix.txt = strconv.Itoa(b.versionRules.MaxVersion-1) + ".0.0"
	if err := b.versions.toReleaseRepoPrefix.updateSemver(); err != nil {
		return err
	}

	return nil
}

// loadVersions will load the latest version from the index.yaml and the version to release from the chart owner upstream repository
// rules:
//   - latest version might not contain a repoPrefixVersion
//   - to release version must not contain a repoPrefixVersion
func (b *Bump) loadVersions() error {
	b.versions = &versions{
		latest:              &version{},
		latestRepoPrefix:    &version{},
		toRelease:           &version{},
		toReleaseRepoPrefix: &version{},
	}

	// Latest version might contain a repoPrefixVersion
	latestRepoPrefix, latestVersion, found, err := getLatestVersionFromIndex(b.assetsVersionsMap[b.target.main])
	if err != nil {
		return err
	}

	// there is still one chart that only has the repo-prefix version like 105.0.0
	// and does not have an app version.
	if found {
		b.versions.latestRepoPrefix.txt = latestRepoPrefix
		if err := b.versions.latestRepoPrefix.updateSemver(); err != nil {
			return err
		}
	}

	b.versions.latest.txt = latestVersion
	if err := b.versions.latest.updateSemver(); err != nil {
		return err
	}

	// toRelease version comes from the chart owner upstream repository
	b.versions.toRelease.txt = b.Pkg.Chart.GetUpstreamVersion()
	if b.versions.toRelease.txt == "" {
		return errChartUpstreamVersion
	}
	if err := b.versions.toRelease.updateSemver(); err != nil {
		return err
	}

	// upstream/(to release version) must not contain a repoPrefixVersion
	if _, _, found := parseRepoPrefixVersionIfAny(b.versions.toRelease.txt); found {
		return errChartUpstreamVersionWrong
	}

	// Check if latestVersion > versionToRelease before continuing
	if b.versions.toRelease.svr.LT(*b.versions.latest.svr) {
		return errBumpVersion
	}

	return nil
}

// getLatestVersionFromIndex will get the latest version written in the index.yaml
// that is not a RC (Release Candidate).
func getLatestVersionFromIndex(versions []lifecycle.Asset) (string, string, bool, error) {
	// get the latest released version from the index.yaml (the first version is the latest; already sorted)
	// but it may be a Release Candidate, so getLatestVersionRecursively will filter that out.
	latestUnparsedVersion := getLatestVersionRecursively(versions)
	if latestUnparsedVersion == "" {
		return "", "", false, errChartLatestVersion
	}

	latestRepoPrefix, latestVersion, found := parseRepoPrefixVersionIfAny(latestUnparsedVersion)
	return latestRepoPrefix, latestVersion, found, nil
}

// getLatestVersionRecursively will get the latest non-RC version from the entry at the index.yaml
func getLatestVersionRecursively(versions []lifecycle.Asset) string {
	if len(versions) == 0 {
		return ""
	}

	latestVersion := versions[0].Version
	if strings.Contains(latestVersion, "-rc") || strings.Contains(latestVersion, "-alpha") || strings.Contains(latestVersion, "-beta") {
		return getLatestVersionRecursively(versions[1:])
	}

	return latestVersion
}

// getCurrentRCsFromIndex will get the corresponding release candidate versions of the chart version being bumped
func getCurrentRCsFromIndex(versions []lifecycle.Asset, toReleasePrefix string) ([]rc, error) {
	if !strings.Contains(versions[0].Version, toReleasePrefix) || toReleasePrefix == "" {
		return nil, nil
	}

	var currentRCs []rc
	for _, v := range versions {
		if !strings.Contains(v.Version, toReleasePrefix) {
			break
		}

		currentRC := rc{
			repoPrefix: &version{},
			appVersion: &version{},
		}

		prefix, app, found := parseRepoPrefixVersionIfAny(v.Version)
		if !found {
			return nil, errors.New("chat version should have a repo prefix")
		}

		currentRC.repoPrefix.txt = prefix
		if err := currentRC.repoPrefix.updateSemver(); err != nil {
			return nil, err
		}

		currentRC.appVersion.txt = app
		if err := currentRC.appVersion.updateSemver(); err != nil {
			return nil, err
		}

		currentRCs = append(currentRCs, currentRC)
	}

	return currentRCs, nil
}

// parseRepoPrefixVersionIfAny will parse the repository prefix version if it exists
func parseRepoPrefixVersionIfAny(unparsedVersion string) (repoPrefix, version string, found bool) {
	found = strings.Contains(unparsedVersion, "+up")
	if found {
		versions := strings.Split(unparsedVersion, "+up")
		repoPrefix = versions[0]
		version = versions[1]
	} else {
		version = unparsedVersion
	}

	return repoPrefix, version, found
}

// applyVersionRules determines the correct repository-specific version prefix for the upcoming release.
//
// The repo prefix follows the format 10X.Y.Z and is independent of the upstream app version.
// Its major component (10X) is dictated by the Rancher branch line (e.g., dev-v2.11 → 107.x.x).
// The minor and patch components are bumped based on the semantic difference with the latest released version.
//
// Branch transition (latestRepoPrefix is empty or differs by exactly 1 major from the rule):
//
//	last version: X.Y.Z+upA.B.C   | branch rule: 105.0.0  → toReleaseRepoPrefix: 105.0.0
//	last version: 104.X.Y+upA.B.C | branch rule: 105.0.0  → toReleaseRepoPrefix: 105.0.0
//
// Same branch line (latestRepoPrefix major == rule major):
//
//	versionOverride "auto" or "": derive patch/minor increment from upstream semver diff
//	versionOverride "patch":      force patch increment, reset minor
//	versionOverride "minor":      force minor increment, reset patch
//
// Any other major version relationship (jump > 1 branch line, or rule behind latest) is a fatal
// misconfiguration and returns an error immediately.
func (b *Bump) applyVersionRules(versionOverride string) error {
	// repoPrefixVersionRule is the minimum allowed repo prefix for this branch line (e.g., "105.0.0").
	repoPrefixVersionRule := b.versionRules.Rules[b.versionRules.BranchVersion].Min
	repoPrefixSemverRule, err := semver.Make(repoPrefixVersionRule)
	if err != nil {
		return err
	}

	// Branch transition: no prior prefix exists, or we moved up exactly one Rancher major.
	// In both cases the repo prefix resets to the branch rule floor (e.g., 105.0.0).
	if b.versions.latestRepoPrefix.txt == "" || (repoPrefixSemverRule.Major-b.versions.latestRepoPrefix.svr.Major == 1) {
		b.versions.toReleaseRepoPrefix.txt = repoPrefixVersionRule
		if err := b.versions.toReleaseRepoPrefix.updateSemver(); err != nil {
			return err
		}
		return nil
	}

	// Guard: jumping more than one branch line, or the rule is behind the latest prefix,
	// indicates a misconfigured branch or a corrupted index — fail fast.
	if (repoPrefixSemverRule.Major-b.versions.latestRepoPrefix.svr.Major > 1) ||
		(repoPrefixSemverRule.Major < b.versions.latestRepoPrefix.svr.Major) {
		return errors.New("difference between major versions is more than 1 or repoPrefix version is lower than latestRepoPrefix version")
	}

	// Same branch line: start from the latest prefix and apply the requested increment.
	b.versions.toReleaseRepoPrefix.txt = b.versions.latestRepoPrefix.txt
	if err := b.versions.toReleaseRepoPrefix.updateSemver(); err != nil {
		return err
	}

	switch versionOverride {
	case "auto", "":
		// Derive the increment automatically from the upstream semver difference.
		// Patch-only bump → increment repo patch. Minor or major bump → increment repo minor, reset patch.
		majorBump := b.versions.toRelease.svr.Major > b.versions.latest.svr.Major
		minorBump := b.versions.toRelease.svr.Minor > b.versions.latest.svr.Minor
		patchBump := b.versions.toRelease.svr.Patch > b.versions.latest.svr.Patch

		if patchBump && !majorBump && !minorBump {
			b.versions.toReleaseRepoPrefix.svr.Patch++
		}
		if minorBump || majorBump {
			b.versions.toReleaseRepoPrefix.svr.Minor++
			b.versions.toReleaseRepoPrefix.svr.Patch = 0
		}
	case "patch":
		b.versions.toReleaseRepoPrefix.txt = b.versions.latestRepoPrefix.txt
		if err := b.versions.toReleaseRepoPrefix.updateSemver(); err != nil {
			return err
		}
		b.versions.toReleaseRepoPrefix.svr.Patch++
		b.versions.toReleaseRepoPrefix.svr.Minor = 0
		b.versions.toReleaseRepoPrefix.updateTxt()
	case "minor":
		b.versions.toReleaseRepoPrefix.txt = b.versions.latestRepoPrefix.txt
		if err := b.versions.toReleaseRepoPrefix.updateSemver(); err != nil {
			return err
		}
		b.versions.toReleaseRepoPrefix.svr.Minor++
		b.versions.toReleaseRepoPrefix.svr.Patch = 0
		b.versions.toReleaseRepoPrefix.updateTxt()
	}

	b.versions.toReleaseRepoPrefix.updateTxt()
	return nil
}
