#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/charts-build-scripts.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/charts-build-scripts.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/charts-build-scripts
if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/charts-build-scripts-darwin
    GOOS=windows go build -ldflags "$LINKFLAGS" -o bin/charts-build-scripts-windows
fi
