name: CI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: Run unit tests
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: latest
          install-mode: goinstall
          only-new-issues: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: Setup goreleaser
        shell: bash
        run: |-
          OS="Linux"
          if [[ ${RUNNER_OS} != "Linux" ]]; then
          	echo "Unsupported OS: ${RUNNER_OS}"
          	exit 1
          fi

          # renovate-local: goreleaser-x86_64
          GORELEASER_VERSION="v2.15.2"
          # renovate-local: goreleaser-x86_64=v2.15.2
          GORELEASER_CHECKSUM_x86_64="0ebdbf0353aba566b969dde746cc4e4806f96c27aa2f3971b229a9df7611fedc"

          ARCH=$(uname -m)
          CHECKSUM="${GORELEASER_CHECKSUM_x86_64}"
          if [[ "${ARCH}" != "x86_64" ]]; then
          	echo "Unsupported architecture: ${ARCH}"
          	exit 1
          fi

          FILE="goreleaser_${OS}_${ARCH}.tar.gz"

          echo "Installing ${FILE}"
          curl -LO "https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/${FILE}"
          echo "${CHECKSUM} ${FILE}" | sha256sum -c
          tar -xf "${FILE}" goreleaser

          if sudo -n true &> /dev/null; then
          	sudo install -m 755 goreleaser /usr/local/bin/goreleaser
          else
          	install -m 755 goreleaser /usr/local/bin/goreleaser
          fi
          rm -f "${FILE}" goreleaser
      - name: Run goreleaser
        shell: bash
        run: |-
          goreleaser build --snapshot
          if [[ ! -f dist/metadata.json ]] || [[ ! -s dist/metadata.json ]]; then
            echo "Missing required file: dist/metadata.json"
            exit 1
          fi
          if [[ ! -f dist/artifacts.json ]] || [[ ! -s dist/artifacts.json ]]; then
            echo "Missing required file: dist/artifacts.json"
            exit 1
          fi
          echo "metadata=$(tr -d '\n\r' < dist/metadata.json)" >> "${GITHUB_OUTPUT}"
          echo "artifacts=$(tr -d '\n\r' < dist/artifacts.json)" >> "${GITHUB_OUTPUT}"
