name: CI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod

      - name: Run Tests(unit, canary, integration)
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          version: latest
          install-mode: goinstall
          only-new-issues: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Setup goreleaser
        shell: bash
        run: |-
          OS="Linux"
          if [[ ${RUNNER_OS} != "Linux" ]]; then
          	echo "Unsupported OS: ${RUNNER_OS}"
          	exit 1
          fi

          # renovate-local: goreleaser-x86_64
          GORELEASER_VERSION="v2.16.0"
          # renovate-local: goreleaser-x86_64=v2.16.0
          GORELEASER_CHECKSUM_x86_64="eaae05b5eba07533bd0f06846b68c808399504784df00c62eb219541fc04e5e2"

          ARCH=$(uname -m)
          CHECKSUM="${GORELEASER_CHECKSUM_x86_64}"
          if [[ "${ARCH}" != "x86_64" ]]; then
          	echo "Unsupported architecture: ${ARCH}"
          	exit 1
          fi

          FILE="goreleaser_${OS}_${ARCH}.tar.gz"

          echo "Installing ${FILE}"
          curl -LO "https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/${FILE}"
          echo "${CHECKSUM} ${FILE}" | sha256sum -c
          tar -xf "${FILE}" goreleaser

          if sudo -n true &> /dev/null; then
          	sudo install -m 755 goreleaser /usr/local/bin/goreleaser
          else
          	install -m 755 goreleaser /usr/local/bin/goreleaser
          fi
          rm -f "${FILE}" goreleaser
      - name: Run goreleaser
        shell: bash
        run: |-
          goreleaser build --snapshot
          if [[ ! -f dist/metadata.json ]] || [[ ! -s dist/metadata.json ]]; then
            echo "Missing required file: dist/metadata.json"
            exit 1
          fi
          if [[ ! -f dist/artifacts.json ]] || [[ ! -s dist/artifacts.json ]]; then
            echo "Missing required file: dist/artifacts.json"
            exit 1
          fi
          echo "metadata=$(tr -d '\n\r' < dist/metadata.json)" >> "${GITHUB_OUTPUT}"
          echo "artifacts=$(tr -d '\n\r' < dist/artifacts.json)" >> "${GITHUB_OUTPUT}"
