name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
  # Run twice in the early morning (UTC) for initial and follow up steps (create pull request and merge)
  schedule:
    - cron: '30 4,6 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    uses: rancher/renovate-config/.github/workflows/renovate-vault.yml@8b94387fbdf3a01548db1a17d707c14cd1c2b1f8 # release
    with:
      logLevel: ${{ inputs.logLevel || 'info' }}
      overrideSchedule: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
    secrets: inherit
